export const authTypes = {
    LOGIN_START: `LOGIN_START`,
    LOGIN_SUCCESS: `LOGIN_SUCCESS`,
    LOGIN_FAILURE: `LOGIN_FAILURE`,
    LOGOUT: `LOGOUT`,
    LOGOUT_START: `LOGOUT_START`,
    LOGOUT_SUCCESS: `LOGOUT_SUCCESS`,
    LOGOUT_FAILURE: `LOGOUT_FAILURE`
}