const BootcampActionTypes = {

    FETCH_BOOTCAMPS_START: "FETCH_BOOTCAMPS_START",
    FETCH_BOOTCAMPS_SUCCESS: "FETCH_BOOTCAMPS_SUCCESS",
    FETCH_BOOTCAMPS_FAILURE: "FETCH_BOOTCAMPS_FAILURE"
}


export default BootcampActionTypes;

